object frm_PCM_System: Tfrm_PCM_System
  Left = 0
  Top = 0
  Caption = 'frm_PCM_System'
  ClientHeight = 479
  ClientWidth = 1051
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OnShow = FormShow
  TextHeight = 13
  object pnl_design: TcxGroupBox
    Left = 0
    Top = 0
    Align = alClient
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 0
    Height = 479
    Width = 1051
    object grpbx_SysInfo_CPU: TcxGroupBox
      AlignWithMargins = True
      Left = 2
      Top = 120
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Prozessor'
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsBold]
      Style.IsFontAssigned = True
      TabOrder = 0
      ExplicitLeft = 3
      ExplicitTop = 121
      ExplicitWidth = 1045
      Height = 87
      Width = 1047
      object lbl_ProcCount: TcxLabel
        Left = 16
        Top = 35
        Caption = 'Prozessoranzahl:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_ProcCount_data: TcxLabel
        Left = 500
        Top = 36
        Caption = 'PROCESSORCOUNT'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_ProcSpeed: TcxLabel
        Left = 16
        Top = 55
        Caption = 'Prozessorgeschwindigkeit:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_ProcSpeed_data: TcxLabel
        Left = 500
        Top = 55
        Caption = 'PROCESSORSPEED'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_ProcType: TcxLabel
        Left = 16
        Top = 16
        Caption = 'Prozessortyp:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_ProcType_data: TcxLabel
        Left = 500
        Top = 16
        Caption = 'PROCESSORTYPE'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
    end
    object grpbx_SysInfo_Ram: TcxGroupBox
      AlignWithMargins = True
      Left = 2
      Top = 213
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Arbeitsspeicher'
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsBold]
      Style.IsFontAssigned = True
      TabOrder = 1
      ExplicitLeft = 3
      ExplicitTop = 214
      ExplicitWidth = 1045
      Height = 66
      Width = 1047
      object lbl_RAMFree: TcxLabel
        Left = 16
        Top = 35
        Caption = 'freier Arbeitsspeicher:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_RAMFree_data: TcxLabel
        Left = 500
        Top = 35
        Caption = 'RAM FREE'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_RAMTotal: TcxLabel
        Left = 16
        Top = 16
        Caption = 'Gesamter Arbeitsspeicher:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_RAMTotal_data: TcxLabel
        Left = 500
        Top = 16
        Caption = 'RAM TOTAL'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
    end
    object grpbx_SysInfo_Resource: TcxGroupBox
      AlignWithMargins = True
      Left = 2
      Top = 285
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Auslastung'
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsBold]
      Style.IsFontAssigned = True
      TabOrder = 2
      ExplicitLeft = 3
      ExplicitTop = 286
      ExplicitWidth = 1045
      Height = 138
      Width = 1047
      object prgbr_ProcUse: TcxProgressBar
        AlignWithMargins = True
        Left = 15
        Top = 97
        Margins.Left = 13
        Margins.Right = 13
        Margins.Bottom = 0
        Align = alTop
        AutoSize = False
        TabOrder = 0
        ExplicitWidth = 1013
        Height = 22
        Width = 1017
      end
      object prgbr_RamUse: TcxProgressBar
        AlignWithMargins = True
        Left = 15
        Top = 47
        Margins.Left = 13
        Margins.Right = 13
        Margins.Bottom = 0
        Align = alTop
        AutoSize = False
        TabOrder = 1
        ExplicitWidth = 1013
        Height = 22
        Width = 1017
      end
      object lbl_ProcUse: TcxLabel
        AlignWithMargins = True
        Left = 15
        Top = 77
        Margins.Left = 13
        Margins.Top = 8
        Margins.Right = 13
        Margins.Bottom = 0
        Align = alTop
        Caption = 'Prozessor:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
        ExplicitLeft = 16
        ExplicitTop = 59
        ExplicitWidth = 1013
      end
      object lbl_RamUse: TcxLabel
        AlignWithMargins = True
        Left = 15
        Top = 27
        Margins.Left = 13
        Margins.Top = 9
        Margins.Right = 13
        Margins.Bottom = 0
        Align = alTop
        Caption = 'Arbeitsspeicher:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
        ExplicitLeft = 16
        ExplicitTop = 5
        ExplicitWidth = 1013
      end
    end
    object grpbx_SysInfo_Sys: TcxGroupBox
      AlignWithMargins = True
      Left = 2
      Top = 8
      Margins.Left = 0
      Margins.Top = 6
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Windows'
      ParentBackground = False
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsBold]
      Style.IsFontAssigned = True
      TabOrder = 3
      ExplicitLeft = 3
      ExplicitTop = 9
      ExplicitWidth = 1045
      Height = 106
      Width = 1047
      object lbl_Graphic: TcxLabel
        Left = 16
        Top = 56
        Caption = 'Grafikaufl'#246'sung:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_Graphic_data: TcxLabel
        Left = 500
        Top = 56
        Caption = 'Label2'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_os: TcxLabel
        Left = 16
        Top = 16
        Caption = 'Betriebssystem:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_os_data: TcxLabel
        Left = 500
        Top = 16
        Caption = 'Label2'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_PCName: TcxLabel
        Left = 16
        Top = 36
        Caption = 'Computername:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_PCName_data: TcxLabel
        Left = 500
        Top = 36
        Caption = 'Label2'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_SysDir: TcxLabel
        Left = 16
        Top = 75
        Caption = 'Systemlaufwerk:'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
      object lbl_SysDir_data: TcxLabel
        Left = 500
        Top = 75
        Caption = 'Label2'
        ParentFont = False
        Style.Font.Charset = DEFAULT_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -11
        Style.Font.Name = 'Tahoma'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        Transparent = True
      end
    end
  end
  object tmr_GetRamUsage: TTimer
    Interval = 500
    OnTimer = tmr_GetRamUsageTimer
    Left = 96
    Top = 521
  end
end
