object frmProgressDialog: TfrmProgressDialog
  Left = 457
  Top = 428
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 65
  ClientWidth = 417
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  Position = poScreenCenter
  OnCreate = FormCreate
  TextHeight = 13
  object pnl_design: TcxGroupBox
    Left = 0
    Top = 0
    PanelStyle.Active = True
    Style.BorderStyle = ebsNone
    TabOrder = 0
    Height = 65
    Width = 417
    object prgbr_Main: TcxProgressBar
      Left = 64
      Top = 31
      AutoSize = False
      Position = 100.000000000000000000
      Properties.BarStyle = cxbsGradientLEDs
      Properties.BeginColor = clWhite
      Properties.EndColor = 6750054
      Properties.PeakValue = 100.000000000000000000
      Style.LookAndFeel.SkinName = ''
      StyleDisabled.LookAndFeel.SkinName = ''
      StyleFocused.LookAndFeel.SkinName = ''
      StyleHot.LookAndFeel.SkinName = ''
      TabOrder = 0
      Height = 19
      Width = 329
    end
    object lNachricht: TcxLabel
      Left = 64
      Top = 8
      AutoSize = False
      Caption = '*'
      TabOrder = 1
      Transparent = True
      Height = 17
      Width = 329
    end
    object ind_wait: TdxActivityIndicator
      Left = 8
      Top = 8
      Width = 42
      Height = 42
      PropertiesClassName = 'TdxActivityIndicatorCircularDotsProperties'
      Properties.AnimationTime = 7500
      Properties.DotSize = 5
    end
  end
end
